# Global Food & Nutrition Database

### Descarga de los archivos

In [1]:
!pip install wget
!pip install pandas
!pip install matplotlib
!pip install scipy
!pip install sweetviz

Requirement already satisfied: wget in ./.venv/lib/python3.14/site-packages (3.2)

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (1.18.1)
Requirement already satisfied: numpy<2.8,>=2.0.0 in ./.venv/lib/python3.14/site-packages (from scipy) (2.5.3)

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: sweetviz in ./.venv/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in ./.venv/lib/python3.14/site-packages (from sweetviz) (3.0.6)
Requirement already satisfied: numpy>=1.16.0 in ./.venv/lib/python3.14/site-packages (from sweetviz) (2.5.3)
Requirement already satisfied: matplotlib>=3.1.3 in ./.venv/lib/python3.14/site-packages (from sweetviz) (3.11.2)
Requirement already satisfied: tqdm>=4.43.0 in ./.venv/lib/python3.14/site-packages (from sweetviz) (4.70.1)
Requirement already satisfied: scipy>=1.3.2 in ./.venv/lib/python3.14/site-packages (from sweetviz) (1.18.1)
Requirement already satisfied: jinja2>=2.11.1 in ./.venv/lib/python3.14/site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in ./.venv/lib/python3.14/site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.14/site-packages (from jinja2>=2.11.1->sweetviz) (3.0.4)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (1.5.1)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=9 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip

In [2]:
from wget import download
from os import path, listdir
import pandas as pd
import numpy as np

if not path.exists("data/global_food.csv"):
    download("", out="data/global_food.csv")
else:
    print("Archivo ya descargado")

dfOG = pd.read_csv("data/global_food.csv", encoding='utf-8')

dfOG.head()

Archivo ya descargado

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000000,0.000000,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000508,0.000203,False,False,False,False,False,False,Branded/Packaged

In [3]:
dfOG.info(verbose=True, show_counts=True)
dfOG.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_name        4785 non-null   str
 1   brands              4751 non-null   str
 2   categories          4913 non-null   str
 3   ingredients         4797 non-null   str
 4   nutriscore_grade    4983 non-null   str
 5   nova_group          4522 non-null   float64
 6   ecoscore_grade      4984 non-null   str
 7   allergens           3332 non-null   str
 8   energy_kcal         4682 non-null   float64
 9   fat_100g            4695 non-null   float64
 10  saturated_fat_100g  4617 non-null   float64
 11  carbs_100g          4676 non-null   float64
 12  sugars_100g         4631 non-null   float64
 13  fiber_100g          3495 non-null   float64
 14  proteins_100g       4690 non-null   float64
 15  salt_100g           4653 non-null   float64
 16  sodium_100g         4653 non-null   float64
 17  contains_gluten     4997 non-null   bool
 18  contains_dairy      4997 non-null   bool
 19  contains_nuts       4997 non-null   bool
 20  contains_soy        4997 non-null   bool
 21  contains_eggs       4997 non-null   bool
 22  contains_fish       4997 non-null   bool
 23  food_type           4997 non-null   str
dtypes: bool(6), float64(10), str(8)
memory usage: 732.1 KB

,nova_group,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g
count,4522.000000,4682.000000,4695.000000,4617.000000,4676.000000,4631.000000,3.495000e+03,4690.000000,4653.000000,4653.000000
mean,3.278859,301.225402,15.997065,5.489583,32.598284,12.368927,1.748567e+09,7.348264,1.477237,0.590895
std,1.033540,221.661070,21.974815,12.451133,133.906873,22.020440,1.033727e+11,11.135688,14.776243,5.910491
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,3.000000,99.000000,1.500000,0.300000,4.800000,1.095000,5.000000e-01,1.700000,0.030000,0.012000
50%,4.000000,295.000000,7.420000,1.500000,19.700000,4.300000,3.000000e+00,6.300000,0.312000,0.125000
75%,4.000000,456.000000,23.000000,6.800000,58.000000,16.000000,6.600000e+00,9.600000,1.000000,0.400000
max,4.000000,5280.000000,554.000000,595.000000,8989.000000,895.000000,6.111242e+12,597.000000,898.000000,359.200000

In [4]:
df = dfOG.copy()

print("Filas antes de limpiar:", len(df))

# eliminamos la columna food type poruqe en todas las filas es el mismo valor
df = df.drop(columns=["food_type"])

# eliminamos las filas que tengan nombre y marca vacios
df = df.dropna(subset=['product_name', 'brands'], how='all')

# eliminamos las columnas repetidas
df.drop_duplicates(inplace=True)

# eliminamos las filas que tengan macros imposibles
macros = [
    "fat_100g", "saturated_fat_100g",
    "carbs_100g", "sugars_100g",
    "fiber_100g", "proteins_100g",
    "salt_100g", "sodium_100g"
]

fuera_rango = (
    df[macros].lt(0) | df[macros].gt(100)
).any(axis=1)

calorias_invalidas = (
    df["energy_kcal"].lt(0) | df["energy_kcal"].gt(900)
)

grasas_invalidas = (
    df["saturated_fat_100g"] > df["fat_100g"]
)

azucares_invalidos = (
    df["sugars_100g"] > df["carbs_100g"]
)

eliminar = (
    fuera_rango |
    calorias_invalidas |
    grasas_invalidas |
    azucares_invalidos
)

# Transformamos las variables cualitativas ordinales a numeros y la agregamos a columnas nuevas (no sabemos si eliminar las anteriores)
notasNutriscore = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5}
df["nutriscore_num"] = df["nutriscore_grade"].map(notasNutriscore)

notasEcoscore = {"A-PLUS": 1, "A": 2, "B": 3, "C": 4, "D": 5, "E": 6, "F": 7}
df["ecoscore_num"] = df["ecoscore_grade"].map(notasEcoscore)


print("Filas a eliminar:", eliminar.sum())

df = df.loc[~eliminar].copy()

print("Filas despues de limpiar:", len(df))


#Creamos la columna de categories_list, donde limpiamos cada categoria y las almacenamos en una lista
#Hacemos lo mismo con los alergenos, para facilitar su limpieza y la cuenta de cuantos hay presentes.

df["categories"] = df["categories"].fillna("").apply(
    lambda x: list(dict.fromkeys(
        cat.strip().split(":", 1)[-1]
        for cat in x.split(",") if cat.strip()
    ))
)

df["allergens"] = df["allergens"].fillna("").apply(
    lambda x: list(dict.fromkeys(
        cat.strip().split(":", 1)[-1]
        for cat in x.split(",") if cat.strip()
    ))
)

alergenos_unicos = sorted(df["allergens"].explode().dropna().unique())

print(alergenos_unicos)
print("Cantidad:", len(alergenos_unicos))

df.head(30)

Filas antes de limpiar: 4997
Filas a eliminar: 28
Filas despues de limpiar: 4871
['abricot', 'abricots', 'acesulfame-potassium', 'alaska-seeiachsfiiet', 'alcool', 'amandes', 'amandes-amygdalus-communis-l', 'amendoins-e-leite', 'anhydride-sulfureux-et-sulfites', 'apple', 'arachides', 'avena', 'avoine', 'avoine-ou-hybrides-et-produits-a-base-de-ces-cereales', 'banana', 'beef', 'ble', 'ble-avoine', 'ble-d-epeautre', 'blé', 'butterfat', 'butterreinfett', 'buzagluten', 'buzaliszt', 'cacahuetes', 'celeri', 'celery', 'cereals-with-gluten', 'chicken', 'citron', 'citron-vert', 'creme-laitiere', 'crustaceans', 'crème', 'cuisine-en-france', 'cultured-nonfat-milk', 'dinkelweizenmehl', 'e150d', 'eggs', 'et-produits-a-base-de-ces-cereales', 'et-produits-a-base-de-ces-noix-macadamia-ternifolia', 'fenilalanina', 'fermentos-lacticos', 'fish', 'fruits-a-coque', 'fruits-à-coque', 'frutos-de-casca-rija', 'gelatin', 'gluten', 'gluten-de-ble', 'haferbasis', 'haselnussgeschmack', 'hazlenuts', 'huhnereieiweisspulver', 'huhnervollei', 'hühnerei-trockeneiweiss', 'isento-de-gluten', 'kiwi', 'kuoritut-soijapavut', 'lait', 'laitier', 'laktose', 'lecithines', 'leite', 'lupin', 'magermilchpulver', 'mandarine', 'mandeln', 'mantequilla', 'metabisulfito-sódico', 'metabisulphite', 'milch', 'milcheiweiss', 'milk', 'molkeneiweisisolat', 'molkeneiweißisolat', 'molkeneweißkonzentrat', 'molluscs', 'moutarde', 'mustard', 'mycoprotein', 'noisettes', 'noisettes-corylus-avellana', 'noix-de-pecan-et-produits-a-base-de-noix-de-pecan-carya-illinoiesis-wangenh-k-koch', 'noix-du-bresil-et-produits-a-base-de-noix-du-bresil-bertholletia-excelsa', 'none', 'not-indicated', 'nusskernmischung', 'nuts', 'oatbran', 'oeuf', 'oeufs', 'orange', 'orge', 'palm', 'peach', 'peanuts', 'phenylalanine', 'pistaches-pistacia-vera', 'pode-conter-vestigios-de-outros-cereais-com-gluten', 'pork', 'puede-contener-trazas-de-frutos-de-cascara-y-o-de-soja', 'pumpkin-seeds', 'rice', 'sarrasin', 'seigle', 'select-roasted-peanuts', 'sesame-seeds', 'sodium-metabisulphite', 'sojabasis', 'sojasaucenpulver', 'soybeans', 'suitable-for-vegans', 'sulphur-dioxide-and-sulphites', 'sunflower-seeds', 'trigo-espelta', 'triticale', 'vollmilchpulver', 'weizenmehl', 'weizenstarke', 'wheatberries', 'yeast', 'œufs']
Cantidad: 123

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,nutriscore_num,ecoscore_num
0,Sidi Ali,سيدي علي,"[beverages-and-beverages-preparations, beverag...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,[],0.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,1.0,NaN
1,Perly,Perly,"[dairies, fermented-foods, fermented-milk-prod...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"[banana, milk]",97.00000,3.0,...,NaN,NaN,False,True,False,False,False,False,NaN,3.0
2,Sidi Ali,Sidi Ali,"[beverages-and-beverages-preparations, beverag...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,[],NaN,NaN,...,0.065000,0.026000,False,False,False,False,False,False,1.0,NaN
3,Eau minérale naturelle,sidi ali,"[beverages-and-beverages-preparations, beverag...",100% mineral water,A,1.0,NOT-APPLICABLE,[],NaN,NaN,...,0.065000,0.026000,False,False,False,False,False,False,1.0,NaN
4,اكوافينا,AQUAFINA,"[beverages-and-beverages-preparations, beverag...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,[],0.00000,0.0,...,0.000508,0.000203,False,False,False,False,False,False,1.0,NaN
5,Lait,Jaouda,"[dairies, meals, milks-liquid-and-powder]",Lait frais pasteurisé demi-écrémé à 15g/l de m...,B,3.0,D,[milk],45.00000,1.5,...,0.225000,0.090000,False,True,False,False,False,False,2.0,5.0
6,Eau De Source,Cristaline,"[beverages-and-beverages-preparations, beverag...",Eau de source,A,1.0,NOT-APPLICABLE,[none],0.00000,0.0,...,0.002750,0.001100,False,False,False,False,False,False,1.0,NaN
7,Fromage Blanc Nature,Milky Food Professional,"[dairies, fermented-foods, fermented-milk-prod...","Ferments lactiques, Présure, Sel.",A,3.0,B,[milk],80.60000,12.0,...,0.000000,0.000000,False,True,False,False,False,False,1.0,3.0
8,uht jaouda 1L,Jaouda,"[dairies, milks-liquid-and-powder, milks]",Lait entier,B,1.0,D,[milk],58.00000,3.0,...,0.000000,0.000000,False,True,False,False,False,False,2.0,5.0
9,Jben,Jaouda,"[dairies, fermented-foods, fermented-milk-prod...","lait frais entier, crème, stabilisants, amidon...",D,4.0,D,[milk],235.00000,21.0,...,0.460000,0.184000,False,True,False,False,False,False,4.0,5.0
10,Ain Saïss,Danone,"[beverages-and-beverages-preparations, beverag...",Eau minérale naturelle,A,1.0,NOT-APPLICABLE,[],0.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,1.0,NaN
11,Eau minéral naturelle,Ain atlas,"[beverages-and-beverages-preparations, beverag...",0800 94 Aïn Atlas EAU MINÉRALE NATURELLE 55 VO...,A,NaN,NOT-APPLICABLE,[],0.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,1.0,NaN
12,6111035000027,Sidi Ali,"[beverages-and-beverages-preparations, beverag...",Composition minérale en mg/\r\nRésidu sec à 11...,A,NaN,NOT-APPLICABLE,[],0.00000,0.0,...,0.006500,0.002600,False,False,False,False,False,False,1.0,NaN
13,Yeast Extract,Marmite,"[spreads, salted-spreads, yeast-extract-spreads]","yeast extract, barley, wheat, oats, rye, salt,...",E,4.0,UNKNOWN,"[celery, gluten]",260.00000,0.5,...,10.800000,4.320000,True,False,False,False,False,False,5.0,NaN
14,NaN,Jaouda,"[dairies, fermented-foods, fermented-milk-prod...","lait ecremé, créme, ferments lactiques. Matièr...",A,1.0,B,[milk],101.00000,6.0,...,0.000000,0.000000,False,True,False,False,False,False,1.0,3.0
15,NaN,Salim,"[dairies, milks-liquid-and-powder, milks]",lait partiellement écrémé,B,1.0,D,[milk],45.00000,1.5,...,0.000000,0.000000,False,True,False,False,False,False,2.0,5.0
16,NaN,lilia,"[plant-based-foods-and-beverages, dairies, pla...",زيوت نباتية مصفاة غير مهدرجة مل طيب نشأ الفرد ...,D,NaN,E,[],675.00000,75.0,...,0.500000,0.200000,False,False,False,False,False,False,4.0,6.0
17,Coca Cola Original Taste,Coca-Cola,"[beverages-and-beverages-preparations, beverag...","Water, fructose - glucose syrup, carbon dioxid...",C,4.0,NOT-APPLICABLE,[],13.30000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,3.0,NaN
18,اكوافينا,pepsi,"[beverages-and-beverages-preparations, beverag...",Aqua,B,1.0,NOT-APPLICABLE,[],0.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,2.0,NaN
19,Prince Goût Chocolat,LU,"[snacks, breakfasts, sweet-snacks]","Céréale 50 % (Farine de blé 34,8 %, farine de ...",E,4.0,D,"[eggs, gluten, milk, soybeans]",465.00000,17.5,...,0.500000,0.200000,True,True,False,True,True,False,5.0,5.0
20,Edelbitterschokolade Mild 90%,"Lindt EXCELLENCE,Lindt","[snacks, sweet-snacks, cocoa-and-its-products]","Kakaomasse, Kakaobutter, fettarmes Kakaopulver...",E,3.0,E,[],592.00000,55.0,...,0.030000,0.012000,False,False,False,False,False,False,5.0,6.0
21,Lindt Excellence Dark 70% Cocoa,Lindt,"[snacks, sweet-snacks, cocoa-and-its-products]","Cocoa mass, sugar, cocoa butter, vanilla. May ...",E,3.0,E,[],561.66348,41.0,...,0.050000,0.020000,False,False,False,False,False,False,5.0,6.0
22,Oulmes natural carbonated water,Les eaux minérales d'Oulmès S.A.,"[beverages-and-beverages-preparations, beverag...",Natural carbonated water 100%,A,NaN,NOT-APPLICABLE,[],NaN,NaN,...,0.078400,0.031400,False,False,False,False,False,False,1.0,NaN
23,Nutella,Ferrero,"[petit-dejeuners, produits-a-tartiner, produit...","Sucre, huile de palme, NOISETTES 13%, LAIT écr...",E,4.0,UNKNOWN,"[milk, nuts, soybeans]",539.00000,30.9,...,0.107000,0.042800,False,True,True,True,False,False,5.0,NaN
24,Cappy PULPY,Coca cola,"[beverages-and-beverages-preparations, plant-b...","Eau, jus et pulpe d'orange, sucre, acidifiants...",E,4.0,B,[],39.00000,0.0,...,0.126000,0.050400,False,False,False,False,False,False,5.0,3.0
25,Tonik,عربي,"[snacks, sweet-snacks, biscuits-and-cakes]","Coffret fourré au cacao (41,6%) et à la vanill...",E,3.0,E,"[gluten, milk, soybeans]",504.00000,22.2,...,0.217000,0.087000,True,True,False,True,False,False,5.0,6.0
26,levure pâtisserie,NaN,"[food-additives, baking-powder-or-raising-agent]","Bicarbonate de sodium, amidon de maïs, pyropho...",NOT-APPLICABLE,4.0,C,[],183.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,NaN,4.0
27,Ain Saiss Eau Minerale Naturelle,Danone,"[beverages-and-beverages-preparations, beverag...","Calcium : 63,5\r\nMagnésium : 35,5\r\nNitratex...",A,NaN,NOT-APPLICABLE,[],0.00000,0.0,...,0.000000,0.000000,False,False,False,False,False,False,1.0,NaN
28,Sésame,Gerblé,"[snacks, sweet-snacks, biscuits-and-cakes]","Farine de blé 57%, sucre de canne roux, huile ...",C,4.0,C,"[gluten, sesame-seeds]",467.00000,18.0,...,0.380000,0.152000,True,False,False,False,False,False,3.0,4.0
30,Ain Atlas,Eau minérale naturelle des Montagnes d'Atlas,"[beverages-and-beverages-preparations, beverag...",Composition Minérale en mg/L \r\nRésidu Sec à ...,A,NaN,NOT-APPLICABLE,[],NaN,NaN,...,0.000000,0.000000,False,False,False,False,False,False,1.0,NaN

In [5]:
import sweetviz as sv

report = sv.analyze(df)
report.show_notebook()

/home/martin/Notes/Fundamentos/TPEspecialFundamentos/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[Summarizing dataframe]                      |          | [  0%]   00:00 -> (? left)

TypeError: unhashable type: 'list'

In [ ]:
import matplotlib.pyplot as plt

# Validamos la primer hipotesis: Mas del 50% de los alimentos contienen gluten

proporcion_gluten = df["contains_gluten"].mean()

if (proporcion_gluten > 0.5):
    print(f"Los productos con gluten superan el 50% ({proporcion_gluten:.1%})")
else:
    print(f"Los productos con gluten no superan el 50% ({proporcion_gluten:.1%})")

conteo = df["contains_gluten"].map({True: 'Con gluten', False: 'Sin gluten'}).value_counts()

plt.pie(
    conteo, 
    labels=conteo.index,
    autopct='%1.1f%%',
    colors=["#90ffa4", "#fef46b"],
    startangle=90
)

plt.title('Distribución de Alimentos según presencia de Gluten')
plt.show()

In [ ]:
import scipy

# Validamos la segunda hipotesis: Los alimentos con mayor cantidad de azucar tienen un nutriscore mas bajo

df_h2 = df[["nutriscore_grade", "nutriscore_num", "sugars_100g"]].copy()

df_h2 = df_h2.dropna()

correlacion = df_h2[["sugars_100g", "nutriscore_num"]].corr(method="spearman").iloc[0, 1]

var1 = "nutriscore_grade"
var2 = "sugars_100g"

df_h2.boxplot(column=var2, by=var1)
plt.title("Distribucion de azucar por cada grado de nutriscore")
plt.legend([f"Correlación: {correlacion:.4f}"], loc="upper left")
plt.suptitle('')
plt.xlabel(var1)
plt.ylabel(var2)

In [ ]:
# Validacion de la primer hipotesis del enunciado

df_grasas = df["saturated_fat_100g"].dropna()
proporcion_grasas = (df_grasas > 5).mean()

if (proporcion_grasas > 0.25):
    print(f"Los productos con altas grasas saturadas superan el 25% ({proporcion_grasas:.1%})")
else:
    print(f"Los productos con altas grasas saturadas no superan el 25% ({proporcion_grasas:.1%})")

conteo = (df_grasas > 5).map({True: 'Alto en grasas saturadas', False: 'Bajo en grasas saturadas'}).value_counts()

plt.pie(
    conteo, 
    labels=conteo.index,
    autopct='%1.1f%%',
    colors=["#9298ff", "#ffde66"],
    startangle=90
)

plt.title('Distribución de Alimentos según alta cantidad de grasas saturadas')
plt.show()

In [ ]:
from scipy.stats import spearmanr

df_h5 = df[["nova_group", "nutriscore_num"]].copy()

df_h5 = df_h5.dropna()

coeficiente, p_valor = spearmanr(
    df_h5["nova_group"],
    df_h5["nutriscore_num"]
)

print("Spearman:", coeficiente)
print("p-valor:", p_valor)

####

tabla = pd.crosstab(
    df_h5["nova_group"],
    df_h5["nutriscore_num"]
)

tabla.plot(
    kind="bar",
    stacked=False,
    color=["darkgreen", "yellowgreen", "yellow", "orange", "red"],
    figsize=(10, 6)
)

plt.xlabel("Grado de procesamiento NOVA")
plt.ylabel("Cantidad de productos")
plt.title("Relación entre NOVA y Nutri-Score")
plt.legend(title="Nutri-Score", labels=["A", "B", "C", "D", "E"])
plt.xticks(rotation=0)
plt.show()