# Global Food & Nutrition Database

### Descarga de los archivos

In [7]:
!pip install wget
!pip install pandas

Requirement already satisfied: wget in ./.venv/lib/python3.14/site-packages (3.2)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [8]:
from wget import download
from os import path, listdir
import pandas as pd
import numpy as np

if not path.exists("data/global_food.csv"):
    download("", out="data/global_food.csv")
else:
    print("Archivo ya descargado")

dfOG = pd.read_csv("data/global_food.csv", encoding='utf-8')

dfOG.head()

ya existe el archivo

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,0.0,4.2,1.4,0.0,0.0,0.000000,0.000000,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,NaN,9.4,NaN,NaN,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000508,0.000203,False,False,False,False,False,False,Branded/Packaged

In [28]:
dfOG.info(verbose=True, show_counts=True)
dfOG.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_name        4785 non-null   str
 1   brands              4751 non-null   str
 2   categories          4913 non-null   str
 3   ingredients         4797 non-null   str
 4   nutriscore_grade    4983 non-null   str
 5   nova_group          4522 non-null   float64
 6   ecoscore_grade      4984 non-null   str
 7   allergens           3332 non-null   str
 8   energy_kcal         4682 non-null   float64
 9   fat_100g            4695 non-null   float64
 10  saturated_fat_100g  4617 non-null   float64
 11  carbs_100g          4676 non-null   float64
 12  sugars_100g         4631 non-null   float64
 13  fiber_100g          3495 non-null   float64
 14  proteins_100g       4690 non-null   float64
 15  salt_100g           4653 non-null   float64
 16  sodium_100g         4653 non-null   float64
 17  contains_gluten     4997 non-null   bool
 18  contains_dairy      4997 non-null   bool
 19  contains_nuts       4997 non-null   bool
 20  contains_soy        4997 non-null   bool
 21  contains_eggs       4997 non-null   bool
 22  contains_fish       4997 non-null   bool
 23  food_type           4997 non-null   str
dtypes: bool(6), float64(10), str(8)
memory usage: 732.1 KB

,nova_group,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g
count,4522.000000,4682.000000,4695.000000,4617.000000,4676.000000,4631.000000,3.495000e+03,4690.000000,4653.000000,4653.000000
mean,3.278859,301.225402,15.997065,5.489583,32.598284,12.368927,1.748567e+09,7.348264,1.477237,0.590895
std,1.033540,221.661070,21.974815,12.451133,133.906873,22.020440,1.033727e+11,11.135688,14.776243,5.910491
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,3.000000,99.000000,1.500000,0.300000,4.800000,1.095000,5.000000e-01,1.700000,0.030000,0.012000
50%,4.000000,295.000000,7.420000,1.500000,19.700000,4.300000,3.000000e+00,6.300000,0.312000,0.125000
75%,4.000000,456.000000,23.000000,6.800000,58.000000,16.000000,6.600000e+00,9.600000,1.000000,0.400000
max,4.000000,5280.000000,554.000000,595.000000,8989.000000,895.000000,6.111242e+12,597.000000,898.000000,359.200000

In [ ]:
df = dfOG

# transformamos los UNKNOWN y los NOT-APPLICABLE en valores nulos
df["nutriscore_grade"] = df["nutriscore_grade"].replace('UNKNOWN', pd.NA)
df["nutriscore_grade"] = df["nutriscore_grade"].replace('NOT-APPLICABLE', pd.NA)

df["ecoscore_grade"] = df["ecoscore_grade"].replace('UNKNOWN', pd.NA)
df["ecoscore_grade"] = df["ecoscore_grade"].replace('NOT-APPLICABLE', pd.NA)

0     NaN
1       B
2     NaN
3     NaN
4     NaN
5       D
6     NaN
7       B
8       D
9       D
10    NaN
11    NaN
12    NaN
13    NaN
14      B
15      D
16      E
17    NaN
18    NaN
19      D
Name: ecoscore_grade, dtype: str